export const ADD_ARTICLE = 'ADD_ARTICLE';
export const UPDATE_SEARCH_TERM = 'UPDATE_SEARCH_TERM';
export const CLEAR_FORM = 'CLEAR_FORM';
export const DATA_LOADED = 'DATA_LOADED';
export const LOAD_DATA_FROM_API = 'LOAD_DATA_FROM_API';
export const UPDATE_AUTOCOMPLETE = 'UPDATE_AUTOCOMPLETE';
