export const teams = [
    { name: "New Jersey Devils", id: 1},
    { name: "New York Islanders", id: 2},
    { name: "New York Rangers", id: 3},
    { name: "Philadelphia Flyers", id: 4},
    { name: "Pittsburgh Penguins", id: 5},
    { name: "Boston Bruins", id: 6},
    { name: "Buffalo Sabres", id: 7},
    { name: "Montreal Canadiens", id: 8},
    { name: "Ottawa Senators", id: 9},
    { name: "Toronto Maple Leafs", id: 10},
    { name: "Carolina Hurricanes", id: 12},
    { name: "Florida Panthers", id: 13},
    { name: "Tampa Bay Lightning", id: 14},
    { name: "Washington Capitals", id: 15},
    { name: "Chicago Blackhawks", id: 16},
    { name: "Detroit Red Wings", id: 17},
    { name: "Boston Bruins", id: 18},
    { name: "Boston Bruins", id: 19},
    { name: "Boston Bruins", id: 20},
    { name: "Boston Bruins", id: 21},
    { name: "Boston Bruins", id: 22},
    { name: "Boston Bruins", id: 23},
    { name: "Boston Bruins", id: 24},
    { name: "Boston Bruins", id: 25},
    { name: "Boston Bruins", id: 26},
    { name: "Boston Bruins", id: 28},
    { name: "Boston Bruins", id: 29},
    { name: "Boston Bruins", id: 30},
    { name: "Boston Bruins", id: 52},
    { name: "Boston Bruins", id: 53},
    { name: "Boston Bruins", id: 54},

    "Buffalo Sabers", 
    "Detroit Red Wings", 
    "Florida Panthers", 
    "Montreal Canadians", 
    "Ottawa Senators", 
    "Tampa Bay Lightning", 
    "Toronto Maple Leafs",
    "Caolina Hurricanes",
    "Columbus Blue Jackets",
    "New Jersey Devils",
    "New York Islanders", 
    "New York Rangers",
    "Philadelphia Flyers",
    "Pittsburgh Penguins", 
    "Washington Captials",
    "Chigago Blackhawks",
    "Colorado Avalanche",
    "Dallas Stars", 
    "Minnesota Wild",
    "Nashville Predators",
    "St. Louis Blues",
    "Winnepeg Jets", 
    "Anahiem Ducks",
    "Arizona Coyotes",
    "Calgary Flames",
    "Edmonton Oilers",
    "Los Angeles Kings",
    "San Jose Sharks",
    "Vancouver Canucks",
    "Vegas Golden Knights"
];